# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c4af6b015a02d86c0d4b7401739c6171f2f9939e8c21237c47508a136ef2cc758383329374acb61d0a5da735ecfa278a77b4d8347efff2422358af1f8e2f13a

test:
  secret_key_base: dcbc35dde172493f72fb5698c973dc3126e2bbed563fe424b15d64ca6b274413c682582f5cf166f753813a7634ae948987c53bdff0af352e878f206f8a200270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
